In [28]:
import cv2
import numpy as np

# Set the path to your image folder and initial frame number
image_folder = '/Users/braydennoh/Downloads/FlocData/slit_resized/'
output_folder = '/Users/braydennoh/Downloads/FlocData/imagetrack/'
start_frame = 560
end_frame = 570

# Iterate through frames
for frame_num in range(start_frame, end_frame + 1):
    # Construct the image path
    image_path = f'{image_folder}/frame_{frame_num:04d}.png'
    
    # Read and process the image
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    equalized_gray = cv2.equalizeHist(gray)
    blurred = cv2.GaussianBlur(equalized_gray, (5, 5), 10)
    ret, thresh = cv2.threshold(blurred, 5, 255, cv2.THRESH_BINARY_INV)
    kernel = np.ones((3, 3), np.uint8)
    cleaned = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
    dilation_kernel = np.ones((3, 3), np.uint8)
    dilated = cv2.dilate(cleaned, dilation_kernel, iterations=5)
    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # Process each contour
    for cnt in contours:
        # Create a mask for the current contour
        mask = np.zeros(gray.shape, np.uint8)
        cv2.drawContours(mask, [cnt], -1, 255, -1)
        masked_img = cv2.bitwise_and(blurred, blurred, mask=mask)
        
        # Compute Laplacian
        laplacian = cv2.Laplacian(masked_img, cv2.CV_64F)
        
        # Threshold the Laplacian to filter out noise
        threshold_value = 0.5 * np.max(laplacian)
        significant_edges = laplacian[laplacian > threshold_value]
        
        if len(significant_edges) > 0:
            edge_statistic = np.percentile(significant_edges, 50)
        else:
            edge_statistic = 0
        
        # Find centroid of contour to place text
        M = cv2.moments(cnt)
        if M["m00"] != 0:
            cX = int(M["m10"] / M["m00"])
            cY = int(M["m01"] / M["m00"])
        else:
            cX, cY = 0, 0
        
        # Draw contour on the image with the edge statistic value label
        cv2.drawContours(image, [cnt], -1, (0, 255, 0), thickness=2)
        cv2.putText(image, f'{edge_statistic:.2f}', (cX - 50, cY), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2, cv2.LINE_AA)
    
    # Save the image with labeled contours
    output_path = f'{output_folder}/frame_{frame_num:04d}_labeled.png'
    cv2.imwrite(output_path, image)

print(f"Images with labeled contours saved from frame_{start_frame:04d} to frame_{end_frame:04d} in {output_folder}.")


Images with labeled contours saved from frame_0560 to frame_0570 in /Users/braydennoh/Downloads/FlocData/imagetrack/.


In [39]:
import cv2
import numpy as np

# Set the path to your image folder and initial frame number
image_folder = '/Users/braydennoh/Downloads/FlocData/slit_resized/'
output_folder = '/Users/braydennoh/Downloads/FlocData/imagetrack/'
start_frame = 560
end_frame = 570

# Iterate through frames
for frame_num in range(start_frame, end_frame + 1):
    # Construct the image path
    image_path = f'{image_folder}/frame_{frame_num:04d}.png'
    
    # Read and process the image
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    equalized_gray = cv2.equalizeHist(gray)
    blurred = cv2.GaussianBlur(equalized_gray, (5, 5), 10)
    ret, thresh = cv2.threshold(blurred, 5, 255, cv2.THRESH_BINARY_INV)
    kernel = np.ones((3, 3), np.uint8)
    cleaned = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
    dilation_kernel = np.ones((3, 3), np.uint8)
    dilated = cv2.dilate(cleaned, dilation_kernel, iterations=5)
    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # Process each contour
    for cnt in contours:
        # Create a mask for the current contour
        mask = np.zeros(gray.shape, np.uint8)
        cv2.drawContours(mask, [cnt], -1, 255, -1)
        masked_img = cv2.bitwise_and(blurred, blurred, mask=mask)
        
        # Compute Laplacian
        laplacian = cv2.Laplacian(masked_img, cv2.CV_64F)
        laplacian_variance = laplacian.var()
        
        # Print Laplacian variance for each particle
        print(f'Frame {frame_num}, Contour {cnt}: Laplacian variance = {laplacian_variance}')
        
        # Find centroid of contour to place text
        M = cv2.moments(cnt)
        if M["m00"] != 0:
            cX = int(M["m10"] / M["m00"])
            cY = int(M["m01"] / M["m00"])
        else:
            cX, cY = 0, 0
        
        # Draw contour on the image with the Laplacian variance label
        cv2.drawContours(image, [cnt], -1, (0, 255, 0), thickness=2)
        cv2.putText(image, f'{laplacian_variance:.2f}', (cX - 50, cY), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2, cv2.LINE_AA)
    
    # Save the image with labeled contours
    output_path = f'{output_folder}/frame_{frame_num:04d}_labeled.png'
    cv2.imwrite(output_path, image)

print(f"Images with labeled contours saved from frame_{start_frame:04d} to frame_{end_frame:04d} in {output_folder}.")


Frame 560, Contour [[[1480  953]]

 [[1479  954]]

 [[1478  954]]

 [[1475  957]]

 [[1475  959]]

 [[1474  960]]

 [[1473  959]]

 [[1472  959]]

 [[1471  958]]

 [[1471  957]]

 [[1464  957]]

 [[1463  956]]

 [[1445  956]]

 [[1445  957]]

 [[1444  958]]

 [[1444  960]]

 [[1443  961]]

 [[1443  962]]

 [[1442  963]]

 [[1442  965]]

 [[1441  966]]

 [[1441  979]]

 [[1442  980]]

 [[1442  983]]

 [[1443  984]]

 [[1443  990]]

 [[1444  991]]

 [[1444  992]]

 [[1446  994]]

 [[1446  995]]

 [[1450  999]]

 [[1451  999]]

 [[1455 1003]]

 [[1456 1003]]

 [[1458 1005]]

 [[1462 1005]]

 [[1463 1006]]

 [[1468 1006]]

 [[1469 1007]]

 [[1470 1007]]

 [[1471 1008]]

 [[1484 1008]]

 [[1485 1007]]

 [[1491 1007]]

 [[1492 1006]]

 [[1493 1007]]

 [[1509 1007]]

 [[1509 1006]]

 [[1510 1005]]

 [[1510 1004]]

 [[1513 1001]]

 [[1515 1001]]

 [[1516 1000]]

 [[1518 1000]]

 [[1520  998]]

 [[1521  998]]

 [[1522  997]]

 [[1522  996]]

 [[1524  994]]

 [[1525  994]]

 [[1530  989]]

 [[15

Frame 561, Contour [[[ 901  916]]

 [[ 900  917]]

 [[ 897  917]]

 [[ 894  920]]

 [[ 894  921]]

 [[ 893  922]]

 [[ 892  922]]

 [[ 890  924]]

 [[ 890  925]]

 [[ 889  926]]

 [[ 888  926]]

 [[ 885  929]]

 [[ 885  931]]

 [[ 883  933]]

 [[ 883  934]]

 [[ 882  935]]

 [[ 881  935]]

 [[ 881  936]]

 [[ 880  937]]

 [[ 879  937]]

 [[ 879  939]]

 [[ 873  945]]

 [[ 873  949]]

 [[ 872  950]]

 [[ 871  950]]

 [[ 871  951]]

 [[ 870  952]]

 [[ 870  953]]

 [[ 867  956]]

 [[ 867  961]]

 [[ 866  962]]

 [[ 866  964]]

 [[ 865  965]]

 [[ 865  979]]

 [[ 866  980]]

 [[ 866  984]]

 [[ 867  985]]

 [[ 867  987]]

 [[ 868  988]]

 [[ 868  998]]

 [[ 869  999]]

 [[ 870  999]]

 [[ 871 1000]]

 [[ 871 1001]]

 [[ 872 1001]]

 [[ 873 1002]]

 [[ 873 1003]]

 [[ 875 1003]]

 [[ 879 1007]]

 [[ 882 1007]]

 [[ 884 1009]]

 [[ 888 1009]]

 [[ 889 1010]]

 [[ 890 1010]]

 [[ 891 1011]]

 [[ 906 1011]]

 [[ 907 1010]]

 [[ 908 1010]]

 [[ 911 1007]]

 [[ 911 1006]]

 [[ 915 1002]]

 [[ 9

Frame 562, Contour [[[ 885 1057]]

 [[ 885 1058]]

 [[ 879 1064]]

 [[ 878 1064]]

 [[ 878 1065]]

 [[ 876 1067]]

 [[ 876 1068]]

 [[ 875 1069]]

 [[ 875 1071]]

 [[ 874 1072]]

 [[ 874 1079]]

 [[ 917 1079]]

 [[ 917 1071]]

 [[ 916 1070]]

 [[ 916 1065]]

 [[ 915 1064]]

 [[ 914 1064]]

 [[ 909 1059]]

 [[ 909 1058]]

 [[ 908 1057]]]: Laplacian variance = 0.10509114582751916
Frame 562, Contour [[[ 760 1025]]

 [[ 758 1027]]

 [[ 757 1027]]

 [[ 756 1028]]

 [[ 755 1028]]

 [[ 753 1030]]

 [[ 751 1030]]

 [[ 750 1031]]

 [[ 750 1033]]

 [[ 748 1035]]

 [[ 748 1036]]

 [[ 747 1037]]

 [[ 746 1037]]

 [[ 741 1042]]

 [[ 740 1042]]

 [[ 739 1043]]

 [[ 738 1043]]

 [[ 737 1044]]

 [[ 736 1044]]

 [[ 735 1045]]

 [[ 734 1045]]

 [[ 734 1046]]

 [[ 733 1047]]

 [[ 732 1047]]

 [[ 732 1049]]

 [[ 730 1051]]

 [[ 730 1052]]

 [[ 729 1053]]

 [[ 727 1053]]

 [[ 725 1055]]

 [[ 725 1063]]

 [[ 724 1064]]

 [[ 724 1079]]

 [[ 807 1079]]

 [[ 807 1066]]

 [[ 806 1065]]

 [[ 806 1063]]

 [[ 805 

Frame 563, Contour [[[ 168  986]]

 [[ 167  987]]

 [[ 164  987]]

 [[ 163  988]]

 [[ 159  988]]

 [[ 158  989]]

 [[ 156  989]]

 [[ 156  990]]

 [[ 155  991]]

 [[ 150  991]]

 [[ 149  992]]

 [[ 145  992]]

 [[ 144  993]]

 [[ 143  993]]

 [[ 142  994]]

 [[ 142  995]]

 [[ 141  996]]

 [[ 140  996]]

 [[ 139  997]]

 [[ 137  997]]

 [[ 137 1004]]

 [[ 136 1005]]

 [[ 135 1005]]

 [[ 135 1006]]

 [[ 134 1007]]

 [[ 134 1028]]

 [[ 136 1030]]

 [[ 136 1032]]

 [[ 137 1033]]

 [[ 137 1034]]

 [[ 138 1035]]

 [[ 138 1036]]

 [[ 141 1039]]

 [[ 142 1039]]

 [[ 143 1040]]

 [[ 143 1041]]

 [[ 144 1042]]

 [[ 144 1044]]

 [[ 145 1045]]

 [[ 146 1045]]

 [[ 147 1046]]

 [[ 148 1046]]

 [[ 150 1048]]

 [[ 150 1049]]

 [[ 151 1050]]

 [[ 163 1050]]

 [[ 164 1049]]

 [[ 168 1049]]

 [[ 169 1048]]

 [[ 175 1048]]

 [[ 176 1047]]

 [[ 177 1047]]

 [[ 180 1044]]

 [[ 180 1043]]

 [[ 181 1042]]

 [[ 184 1042]]

 [[ 185 1041]]

 [[ 188 1041]]

 [[ 190 1039]]

 [[ 191 1039]]

 [[ 192 1038]]

 [[ 1

Frame 564, Contour [[[1025 1044]]

 [[1023 1046]]

 [[1023 1047]]

 [[1021 1049]]

 [[1020 1049]]

 [[1019 1050]]

 [[1018 1050]]

 [[1017 1051]]

 [[1013 1051]]

 [[1011 1053]]

 [[1010 1053]]

 [[1009 1054]]

 [[1007 1054]]

 [[1004 1057]]

 [[1003 1057]]

 [[1001 1059]]

 [[1000 1059]]

 [[ 999 1060]]

 [[ 999 1062]]

 [[ 998 1063]]

 [[ 998 1067]]

 [[ 995 1070]]

 [[ 993 1070]]

 [[ 992 1071]]

 [[ 992 1079]]

 [[1055 1079]]

 [[1055 1070]]

 [[1054 1069]]

 [[1054 1061]]

 [[1053 1061]]

 [[1052 1060]]

 [[1052 1057]]

 [[1051 1056]]

 [[1051 1054]]

 [[1049 1052]]

 [[1049 1051]]

 [[1048 1051]]

 [[1043 1046]]

 [[1042 1046]]

 [[1040 1044]]]: Laplacian variance = 0.011239390431168495
Frame 564, Contour [[[417 903]]

 [[416 904]]

 [[414 904]]

 [[411 907]]

 [[410 907]]

 [[410 908]]

 [[409 909]]

 [[408 909]]

 [[407 910]]

 [[405 910]]

 [[403 912]]

 [[402 912]]

 [[401 913]]

 [[400 913]]

 [[400 914]]

 [[395 919]]

 [[395 926]]

 [[394 927]]

 [[394 941]]

 [[398 945]]


Frame 565, Contour [[[ 398 1040]]

 [[ 396 1042]]

 [[ 395 1042]]

 [[ 393 1044]]

 [[ 392 1044]]

 [[ 392 1045]]

 [[ 391 1046]]

 [[ 390 1046]]

 [[ 389 1047]]

 [[ 388 1047]]

 [[ 386 1049]]

 [[ 385 1049]]

 [[ 384 1050]]

 [[ 383 1050]]

 [[ 382 1051]]

 [[ 381 1051]]

 [[ 381 1052]]

 [[ 379 1054]]

 [[ 379 1055]]

 [[ 378 1056]]

 [[ 378 1057]]

 [[ 377 1058]]

 [[ 377 1059]]

 [[ 376 1060]]

 [[ 376 1062]]

 [[ 375 1063]]

 [[ 375 1077]]

 [[ 376 1078]]

 [[ 376 1079]]

 [[ 429 1079]]

 [[ 429 1068]]

 [[ 428 1067]]

 [[ 428 1065]]

 [[ 427 1064]]

 [[ 427 1062]]

 [[ 426 1061]]

 [[ 426 1059]]

 [[ 424 1057]]

 [[ 424 1056]]

 [[ 422 1054]]

 [[ 422 1053]]

 [[ 421 1052]]

 [[ 421 1051]]

 [[ 420 1050]]

 [[ 420 1048]]

 [[ 418 1046]]

 [[ 418 1045]]

 [[ 417 1044]]

 [[ 417 1042]]

 [[ 415 1040]]]: Laplacian variance = 0.08312837577137237
Frame 565, Contour [[[1615 1011]]

 [[1613 1013]]

 [[1613 1014]]

 [[1612 1015]]

 [[1610 1015]]

 [[1610 1016]]

 [[1609 1017]]

 [[1607 

Frame 566, Contour [[[ 356  988]]

 [[ 355  989]]

 [[ 345  989]]

 [[ 344  990]]

 [[ 342  990]]

 [[ 341  991]]

 [[ 336  991]]

 [[ 335  992]]

 [[ 334  992]]

 [[ 333  993]]

 [[ 332  993]]

 [[ 330  995]]

 [[ 325  995]]

 [[ 323  997]]

 [[ 322  997]]

 [[ 321  998]]

 [[ 320  998]]

 [[ 320 1014]]

 [[ 321 1015]]

 [[ 321 1017]]

 [[ 320 1018]]

 [[ 320 1019]]

 [[ 319 1020]]

 [[ 319 1023]]

 [[ 318 1024]]

 [[ 318 1038]]

 [[ 319 1039]]

 [[ 319 1045]]

 [[ 320 1046]]

 [[ 320 1067]]

 [[ 321 1068]]

 [[ 321 1070]]

 [[ 320 1071]]

 [[ 320 1079]]

 [[ 386 1079]]

 [[ 386 1072]]

 [[ 388 1070]]

 [[ 388 1067]]

 [[ 389 1066]]

 [[ 389 1063]]

 [[ 390 1062]]

 [[ 390 1061]]

 [[ 391 1060]]

 [[ 391 1059]]

 [[ 392 1058]]

 [[ 392 1051]]

 [[ 393 1050]]

 [[ 394 1050]]

 [[ 394 1038]]

 [[ 393 1037]]

 [[ 393 1036]]

 [[ 392 1035]]

 [[ 392 1005]]

 [[ 391 1004]]

 [[ 391 1002]]

 [[ 390 1001]]

 [[ 390  996]]

 [[ 388  996]]

 [[ 386  994]]

 [[ 386  993]]

 [[ 385  993]]

 [[ 3

Frame 567, Contour [[[1516  958]]

 [[1516  971]]

 [[1517  972]]

 [[1517  976]]

 [[1530  976]]

 [[1531  975]]

 [[1531  960]]

 [[1529  958]]]: Laplacian variance = 0.6713310185185185
Frame 567, Contour [[[ 796  957]]

 [[ 794  959]]

 [[ 793  959]]

 [[ 793  961]]

 [[ 792  962]]

 [[ 791  962]]

 [[ 791  963]]

 [[ 790  964]]

 [[ 790  965]]

 [[ 789  966]]

 [[ 787  966]]

 [[ 785  968]]

 [[ 784  968]]

 [[ 783  969]]

 [[ 781  969]]

 [[ 780  970]]

 [[ 779  970]]

 [[ 779  974]]

 [[ 778  975]]

 [[ 774  975]]

 [[ 774  976]]

 [[ 773  977]]

 [[ 772  977]]

 [[ 771  978]]

 [[ 771  983]]

 [[ 770  984]]

 [[ 763  984]]

 [[ 761  986]]

 [[ 761  990]]

 [[ 759  992]]

 [[ 754  992]]

 [[ 753  993]]

 [[ 752  993]]

 [[ 752  994]]

 [[ 751  995]]

 [[ 751 1009]]

 [[ 752 1009]]

 [[ 755 1012]]

 [[ 755 1013]]

 [[ 756 1014]]

 [[ 756 1016]]

 [[ 757 1017]]

 [[ 757 1018]]

 [[ 760 1021]]

 [[ 760 1024]]

 [[ 764 1028]]

 [[ 764 1029]]

 [[ 765 1030]]

 [[ 765 1032]]

 [[ 766 1

Frame 568, Contour [[[1129  920]]

 [[1128  921]]

 [[1127  921]]

 [[1126  922]]

 [[1125  922]]

 [[1124  923]]

 [[1120  923]]

 [[1119  924]]

 [[1118  924]]

 [[1117  925]]

 [[1117  926]]

 [[1114  929]]

 [[1114  930]]

 [[1112  932]]

 [[1112  933]]

 [[1111  934]]

 [[1111  935]]

 [[1110  936]]

 [[1110  937]]

 [[1109  938]]

 [[1109  939]]

 [[1106  942]]

 [[1106  943]]

 [[1104  945]]

 [[1104  946]]

 [[1103  947]]

 [[1103  948]]

 [[1102  949]]

 [[1102  951]]

 [[1101  952]]

 [[1101  970]]

 [[1100  971]]

 [[1099  971]]

 [[1099  972]]

 [[1098  973]]

 [[1098  976]]

 [[1097  977]]

 [[1097  981]]

 [[1095  983]]

 [[1095 1000]]

 [[1096 1001]]

 [[1096 1002]]

 [[1097 1003]]

 [[1097 1005]]

 [[1098 1006]]

 [[1098 1012]]

 [[1099 1013]]

 [[1099 1014]]

 [[1100 1014]]

 [[1103 1017]]

 [[1104 1017]]

 [[1105 1018]]

 [[1107 1018]]

 [[1108 1019]]

 [[1122 1019]]

 [[1124 1017]]

 [[1125 1017]]

 [[1128 1014]]

 [[1128 1013]]

 [[1135 1006]]

 [[1135 1005]]

 [[11

Frame 569, Contour [[[1435  965]]

 [[1434  966]]

 [[1432  966]]

 [[1431  967]]

 [[1430  967]]

 [[1430  968]]

 [[1423  975]]

 [[1423  976]]

 [[1422  977]]

 [[1421  977]]

 [[1419  979]]

 [[1418  979]]

 [[1417  980]]

 [[1415  980]]

 [[1413  982]]

 [[1412  982]]

 [[1409  985]]

 [[1409  986]]

 [[1408  987]]

 [[1408  989]]

 [[1407  990]]

 [[1407 1014]]

 [[1408 1015]]

 [[1408 1020]]

 [[1410 1022]]

 [[1410 1024]]

 [[1411 1025]]

 [[1411 1026]]

 [[1412 1027]]

 [[1412 1030]]

 [[1414 1032]]

 [[1414 1033]]

 [[1417 1036]]

 [[1417 1038]]

 [[1418 1039]]

 [[1418 1040]]

 [[1419 1040]]

 [[1426 1047]]

 [[1427 1047]]

 [[1428 1048]]

 [[1441 1048]]

 [[1442 1047]]

 [[1442 1046]]

 [[1443 1045]]

 [[1444 1045]]

 [[1445 1044]]

 [[1445 1043]]

 [[1446 1042]]

 [[1446 1040]]

 [[1447 1039]]

 [[1447 1021]]

 [[1446 1020]]

 [[1446 1014]]

 [[1449 1011]]

 [[1449 1008]]

 [[1450 1007]]

 [[1450 1003]]

 [[1451 1002]]

 [[1452 1002]]

 [[1452 1001]]

 [[1453 1000]]

 [[14

Frame 570, Contour [[[ 490 1040]]

 [[ 489 1041]]

 [[ 484 1041]]

 [[ 483 1042]]

 [[ 480 1042]]

 [[ 479 1043]]

 [[ 476 1043]]

 [[ 475 1044]]

 [[ 472 1044]]

 [[ 471 1045]]

 [[ 469 1045]]

 [[ 468 1046]]

 [[ 467 1046]]

 [[ 467 1051]]

 [[ 466 1052]]

 [[ 465 1052]]

 [[ 465 1055]]

 [[ 463 1057]]

 [[ 463 1060]]

 [[ 462 1061]]

 [[ 462 1078]]

 [[ 463 1079]]

 [[ 512 1079]]

 [[ 514 1077]]

 [[ 517 1077]]

 [[ 517 1076]]

 [[ 518 1075]]

 [[ 520 1077]]

 [[ 521 1077]]

 [[ 522 1078]]

 [[ 522 1079]]

 [[ 546 1079]]

 [[ 553 1072]]

 [[ 554 1072]]

 [[ 554 1071]]

 [[ 558 1067]]

 [[ 558 1066]]

 [[ 559 1065]]

 [[ 559 1063]]

 [[ 560 1062]]

 [[ 560 1045]]

 [[ 559 1044]]

 [[ 558 1044]]

 [[ 557 1043]]

 [[ 556 1043]]

 [[ 555 1042]]

 [[ 541 1042]]

 [[ 540 1043]]

 [[ 536 1043]]

 [[ 535 1044]]

 [[ 532 1044]]

 [[ 531 1045]]

 [[ 526 1045]]

 [[ 525 1046]]

 [[ 520 1046]]

 [[ 519 1047]]

 [[ 517 1047]]

 [[ 516 1046]]

 [[ 513 1046]]

 [[ 512 1045]]

 [[ 511 1045]]

 [[ 5

In [43]:
import cv2
import numpy as np

# Set the path to your image folder and initial frame number
image_folder = '/Users/braydennoh/Downloads/FlocData/slit_resized/'
output_folder = '/Users/braydennoh/Downloads/FlocData/imagetrack/'
start_frame = 560
end_frame = 600

# Iterate through frames
for frame_num in range(start_frame, end_frame + 1):
    # Construct the image path
    image_path = f'{image_folder}/frame_{frame_num:04d}.png'
    
    # Read and process the image
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    equalized_gray = cv2.equalizeHist(gray)
    blurred = cv2.GaussianBlur(equalized_gray, (5, 5), 10)
    ret, thresh = cv2.threshold(blurred, 10, 255, cv2.THRESH_BINARY_INV)
    kernel = np.ones((3, 3), np.uint8)
    cleaned = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
    dilation_kernel = np.ones((3, 3), np.uint8)
    dilated = cv2.dilate(cleaned, dilation_kernel, iterations=5)
    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # Process each contour
    for cnt in contours:
        # Create a mask for the current contour
        mask = np.zeros(gray.shape, np.uint8)
        cv2.drawContours(mask, [cnt], -1, 255, -1)
        masked_img = cv2.bitwise_and(blurred, blurred, mask=mask)
        
        # Compute Sobel gradients and their magnitude
        sobelx = cv2.Sobel(masked_img, cv2.CV_64F, 1, 0, ksize=5)
        sobely = cv2.Sobel(masked_img, cv2.CV_64F, 0, 1, ksize=5)
        sobel_magnitude = cv2.magnitude(sobelx, sobely)
        sobel_variance = sobel_magnitude.var()
        
        # Print Sobel variance for each particle
        
        # Find centroid of contour to place text
        M = cv2.moments(cnt)
        if M["m00"] != 0:
            cX = int(M["m10"] / M["m00"])
            cY = int(M["m01"] / M["m00"])
        else:
            cX, cY = 0, 0
        
        # Draw contour on the image with the Sobel variance label
        cv2.drawContours(image, [cnt], -1, (0, 255, 0), thickness=2)
        cv2.putText(image, f'{sobel_variance:.2f}', (cX - 50, cY), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2, cv2.LINE_AA)
    
    # Save the image with labeled contours
    output_path = f'{output_folder}/frame_{frame_num:04d}_labeled.png'
    cv2.imwrite(output_path, image)

